OnlineShoping/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main/urls.py
from django.urls import path,include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns=[
    path('',views.home,name='home'),
    path('search',views.search,name='search'),
    path('category-list',views.category_list,name='category-list'),
    path('brand-list',views.brand_list,name='brand-list'),
    path('product-list',views.product_list,name='product-list'),
    path('category-product-list/<int:cat_id>', views.category_product_list, name='category-product-list'),
    path('brand-product-list/<int:brand_id>', views.brand_product_list, name='brand-product-list'),
    path('product/<str:slug>/<int:id>', views.product_detail, name='product_detail'),
    path('filter-data', views.filter_data, name='filter_data'),
    path('load-more-data', views.load_more_data, name='load_more_data'),
    path('add-to-cart', views.add_to_cart, name='add_to_cart'),
    path('cart', views.cart_list, name='cart'),
    path('delete-from-cart', views.delete_cart_item, name='delete-from-cart'),
    path('update-cart', views.update_cart_item, name='update-cart'),
    path('accounts/signup', views.signup, name='signup'),
    path('checkout', views.checkout, name='checkout'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-done/', views.payment_done, name='payment_done'),
    path('payment-cancelled/', views.payment_canceled, name='payment_cancelled'),
    path('save-review/<int:pid>', views.save_review, name='save-review'),
    # User Section Start
    path('my-dashboard', views.my_dashboard, name='my_dashboard'),
    path('my-orders', views.my_orders, name='my_orders'),
    path('my-orders-items/<int:id>', views.my_order_items, name='my_order_items'),
    # End

    # Wishlist
    path('add-wishlist', views.add_wishlist, name='add_wishlist'),
    path('my-wishlist', views.my_wishlist, name='my_wishlist'),
    # My Reviews
    path('my-reviews', views.my_reviews, name='my-reviews'),
 # My AddressBook
    path('my-addressbook',views.my_addressbook, name='my-addressbook'),
    path('add-address', views.save_address, name='add-address'),
    path('activate-address', views.activate_address, name='activate-address'),
    path('update-address/<int:id>', views.update_address, name='update-address'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User
# Create your models here.
# Banner
class Banner(models.Model):
    img=models.ImageField(upload_to="banner_imgs/")
    alt_text=models.CharField(max_length=300)

    class Meta:
        verbose_name_plural = '1. Banners'

    def image_tag(self):
        return mark_safe('<img src="%s" width="100" />' % (self.img.url))


    def __str__(self):
        return self.alt_text


# Category
class Category(models.Model):
    title=models.CharField(max_length=100)
    image=models.ImageField(upload_to="cat_imgs/")

    class Meta:
        verbose_name_plural = '2. Categories'

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title


# Brand
class Brand(models.Model):
    title=models.CharField(max_length=100)
    image=models.ImageField(upload_to="brand_imgs/")

    class Meta:
        verbose_name_plural='3. Brands'

    def __str__(self):
        return self.title

# Color
class Color(models.Model):
    title=models.CharField(max_length=100)
    color_code=models.CharField(max_length=100)

    class Meta:
        verbose_name_plural='4. Colors'

    def color_bg(self):
        return mark_safe('<div style="width:30px; height:30px; background-color:%s"></div>' % (self.color_code))


    def __str__(self):
        return self.title

# Size
class Size(models.Model):
    title=models.CharField(max_length=100)

    class Meta:
        verbose_name_plural='5. Sizes'

    def __str__(self):
        return self.title

# Product Model
class Product(models.Model):
    title=models.CharField(max_length=200)
    slug=models.CharField(max_length=400)
    detail=models.TextField()
    specs=models.TextField()

    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    brand=models.ForeignKey(Brand,on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    status=models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)
    class Meta:
        verbose_name_plural = '6. Products'

    def __str__(self):
        return self.title

# Product Attribute
class ProductAttribute(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    color=models.ForeignKey(Color,on_delete=models.CASCADE)
    size=models.ForeignKey(Size,on_delete=models.CASCADE)
    price=models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to="product_imgs/", null=True)

    class Meta:
        verbose_name_plural='7. ProductAttributes'

    def __str__(self):
        return self.product.title

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

# Order
status_choice=(
        ('process','In Process'),
        ('shipped','Shipped'),
        ('delivered','Delivered'),
    )
class CartOrder(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    total_amt=models.FloatField()
    paid_status=models.BooleanField(default=False)
    order_dt=models.DateTimeField(auto_now_add=True)
    order_status=models.CharField(choices=status_choice,default='process',max_length=150)

    class Meta:
        verbose_name_plural='8. Orders'

# OrderItems
class CartOrderItems(models.Model):
    order=models.ForeignKey(CartOrder,on_delete=models.CASCADE)
    invoice_no=models.CharField(max_length=150)
    item=models.CharField(max_length=150)
    image=models.CharField(max_length=200)
    qty=models.IntegerField()
    price=models.FloatField()
    total=models.FloatField()

    class Meta:
        verbose_name_plural='9. Order Items'

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" />' % (self.image))

# Product Review
RATING=(
    (1,'1'),
    (2,'2'),
    (3,'3'),
    (4,'4'),
    (5,'5'),
)
class ProductReview(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    review_text=models.TextField()
    review_rating=models.CharField(choices=RATING,max_length=150)

    class Meta:
        verbose_name_plural='Reviews'

    def get_review_rating(self):
        return self.review_rating

# WishList
class Wishlist(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural='Wishlist'


# AddressBook
class UserAddressBook(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=50, null=True)
    address = models.TextField()
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'AddressBook'

main/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse,HttpResponse
from .models import Banner, Category, Brand, Product, ProductAttribute, CartOrder, CartOrderItems, ProductReview, \
	Wishlist, UserAddressBook
from django.db.models import Max,Min,Count,Avg
from django.db.models.functions import ExtractMonth
from django.template.loader import render_to_string
from .forms import SignupForm, ReviewAdd, AddressBookForm
from django.contrib.auth import login,authenticate
from django.contrib.auth.decorators import login_required
#paypal
from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm

# Create your views here.
# Home Page
def home(request):
	banners = Banner.objects.all().order_by('-id')
	data = Product.objects.filter(is_featured=True).order_by('-id')
	return render(request, 'index.html', {'data': data, 'banners': banners})


# Category
def category_list(request):
    data = Category.objects.all().order_by('-id')
    return render(request, 'category_list.html', {'data': data})

# Brand
def brand_list(request):
    data=Brand.objects.all().order_by('-id')
    return render(request,'brand_list.html',{'data':data})

# Product List
def product_list(request):
	total_data=Product.objects.count()
	data=Product.objects.all().order_by('-id')[:6]
	min_price=ProductAttribute.objects.aggregate(Min('price'))
	max_price=ProductAttribute.objects.aggregate(Max('price'))
	return render(request,'product_list.html',
		{
			'data':data,
			'total_data':total_data,
			'min_price':min_price,
			'max_price':max_price,
		}
		)


# Product List According to Category
def category_product_list(request,cat_id):
	category=Category.objects.get(id=cat_id)
	data=Product.objects.filter(category=category).order_by('-id')
	return render(request,'category_product_list.html',{
			'data':data
			})

# Product List According to Brand
def brand_product_list(request,brand_id):
	brand=Brand.objects.get(id=brand_id)
	data=Product.objects.filter(brand=brand).order_by('-id')
	return render(request,'category_product_list.html',{
			'data':data,
			})

# Product Detail
def product_detail(request,slug,id):
	product=Product.objects.get(id=id)
	related_products=Product.objects.filter(category=product.category).exclude(id=id)[:4]
	colors=ProductAttribute.objects.filter(product=product).values('color__id','color__title','color__color_code').distinct()
	sizes=ProductAttribute.objects.filter(product=product).values('size__id','size__title','price','color__id').distinct()
	reviewForm=ReviewAdd()

	# Check
	canAdd=True
	reviewCheck=ProductReview.objects.filter(user=request.user,product=product).count()
	if request.user.is_authenticated:
		if reviewCheck > 0:
			canAdd=False
	# End

	# Fetch reviews
	reviews=ProductReview.objects.filter(product=product)
	# End

	# Fetch avg rating for reviews
	avg_reviews=ProductReview.objects.filter(product=product).aggregate(avg_rating=Avg('review_rating'))
	# End

	return render(request, 'product_detail.html',{'data':product,'related':related_products,'colors':colors,'sizes':sizes,'reviewForm':reviewForm,'canAdd':canAdd,'reviews':reviews,'avg_reviews':avg_reviews})


# Search
def search(request):
	q=request.GET['q']
	data=Product.objects.filter(title__icontains=q).order_by('-id')
	return render(request,'search.html',{'data':data})


# Filter Data
def filter_data(request):
	colors=request.GET.getlist('color[]')
	categories=request.GET.getlist('category[]')
	brands=request.GET.getlist('brand[]')
	sizes=request.GET.getlist('size[]')
	minPrice=request.GET['minPrice']
	maxPrice=request.GET['maxPrice']
	allProducts=Product.objects.all().order_by('-id').distinct()
	allProducts=allProducts.filter(productattribute__price__gte=minPrice)
	allProducts=allProducts.filter(productattribute__price__lte=maxPrice)
	if len(colors)>0:
		allProducts=allProducts.filter(productattribute__color__id__in=colors).distinct()
	if len(categories)>0:
		allProducts=allProducts.filter(category__id__in=categories).distinct()
	if len(brands)>0:
		allProducts=allProducts.filter(brand__id__in=brands).distinct()
	if len(sizes)>0:
		allProducts=allProducts.filter(productattribute__size__id__in=sizes).distinct()
	t=render_to_string('ajax/product-list.html',{'data':allProducts})
	return JsonResponse({'data':t})

# Load More
def load_more_data(request):
	offset=int(request.GET['offset'])
	limit=int(request.GET['limit'])
	data=Product.objects.all().order_by('-id')[offset:offset+limit]
	t=render_to_string('ajax/product-list.html',{'data':data})
	return JsonResponse({'data':t}
)

# Add to cart
def add_to_cart(request):
	# del request.session['cartdata']
	cart_p={}
	cart_p[str(request.GET['id'])]={
		'image':request.GET['image'],
		'title':request.GET['title'],
		'qty':request.GET['qty'],
		'price':request.GET['price'],
	}
	if 'cartdata' in request.session:
		if str(request.GET['id']) in request.session['cartdata']:
			cart_data=request.session['cartdata']
			cart_data[str(request.GET['id'])]['qty']=int(cart_p[str(request.GET['id'])]['qty'])
			cart_data.update(cart_data)
			request.session['cartdata']=cart_data
		else:
			cart_data=request.session['cartdata']
			cart_data.update(cart_p)
			request.session['cartdata']=cart_data
	else:
		request.session['cartdata']=cart_p
	return JsonResponse({'data':request.session['cartdata'],'totalitems':len(request.session['cartdata'])})

# Cart List Page
def cart_list(request):
	total_amt=0
	if 'cartdata' in request.session:
		for p_id,item in request.session['cartdata'].items():
			total_amt+=int(item['qty'])*float(item['price'])
		return render(request, 'cart.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})
	else:
		return render(request, 'cart.html',{'cart_data':'','totalitems':0,'total_amt':total_amt})

# Delete Cart Item
def delete_cart_item(request):
	p_id=str(request.GET['id'])
	if 'cartdata' in request.session:
		if p_id in request.session['cartdata']:
			cart_data=request.session['cartdata']
			del request.session['cartdata'][p_id]
			request.session['cartdata']=cart_data
	total_amt=0
	for p_id,item in request.session['cartdata'].items():
		total_amt+=int(item['qty'])*float(item['price'])
	t=render_to_string('ajax/cart-list.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})
	return JsonResponse({'data':t,'totalitems':len(request.session['cartdata'])})

# Update Cart Item
def update_cart_item(request):
	p_id=str(request.GET['id'])
	p_qty=request.GET['qty']
	if 'cartdata' in request.session:
		if p_id in request.session['cartdata']:
			cart_data=request.session['cartdata']
			cart_data[str(request.GET['id'])]['qty']=p_qty
			request.session['cartdata']=cart_data
	total_amt=0
	for p_id,item in request.session['cartdata'].items():
		total_amt+=int(item['qty'])*float(item['price'])
	t=render_to_string('ajax/cart-list.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})
	return JsonResponse({'data':t,'totalitems':len(request.session['cartdata'])})

# Signup Form
def signup(request):
	if request.method=='POST':
		form=SignupForm(request.POST)
		if form.is_valid():
			form.save()
			username=form.cleaned_data.get('username')
			pwd=form.cleaned_data.get('password1')
			user=authenticate(username=username,password=pwd)
			login(request, user)
			return redirect('home')
	form=SignupForm
	return render(request, 'registration/signup.html',{'form':form})

# Checkout
@login_required
def checkout(request):
	total_amt=0
	totalAmt=0
	if 'cartdata' in request.session:
		for p_id,item in request.session['cartdata'].items():
			totalAmt+=int(item['qty'])*float(item['price'])
		# Order
		order=CartOrder.objects.create(
				user=request.user,
				total_amt=totalAmt
			)
		# End
		for p_id,item in request.session['cartdata'].items():
			total_amt+=int(item['qty'])*float(item['price'])
			# OrderItems
			items=CartOrderItems.objects.create(
				order=order,
				invoice_no='INV-'+str(order.id),
				item=item['title'],
				image=item['image'],
				qty=item['qty'],
				price=item['price'],
				total=float(item['qty'])*float(item['price'])
				)
			# End
		# Process Payment
		host = request.get_host()
		paypal_dict = {
		    'business': settings.PAYPAL_RECEIVER_EMAIL,
		    'amount': total_amt,
		    'item_name': 'OrderNo-'+str(order.id),
		    'invoice': 'INV-'+str(order.id),
		    'currency_code': 'USD',
		    'notify_url': 'http://{}{}'.format(host,reverse('paypal-ipn')),
		    'return_url': 'http://{}{}'.format(host,reverse('payment_done')),
		    'cancel_return': 'http://{}{}'.format(host,reverse('payment_cancelled')),
		}
		form = PayPalPaymentsForm(initial=paypal_dict)
		address=UserAddressBook.objects.filter(user=request.user,status=True).first()
		return render(request, 'checkout.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt,'form':form,'address':address})

@csrf_exempt
def payment_done(request):
	returnData=request.POST
	return render(request, 'payment-success.html',{'data':returnData})


@csrf_exempt
def payment_canceled(request):
	return render(request, 'payment-fail.html')

# Save Review
def save_review(request,pid):
	product=Product.objects.get(pk=pid)
	user=request.user
	review=ProductReview.objects.create(
		user=user,
		product=product,
		review_text=request.POST['review_text'],
		review_rating=request.POST['review_rating'],
		)
	data={
		'user':user.username,
		'review_text':request.POST['review_text'],
		'review_rating':request.POST['review_rating']
	}

	# Fetch avg rating for reviews
	avg_reviews=ProductReview.objects.filter(product=product).aggregate(avg_rating=Avg('review_rating'))
	# End

	return JsonResponse({'bool':True,'data':data,'avg_reviews':avg_reviews})

# User Dashboard
import calendar
def my_dashboard(request):

main/templates/brand_product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
.product-card {
   margin-bottom: 20px;

}

.product-card h5 {
   margin-bottom: 0;
}

.product-card h5 a {
   text-decoration: none;
   color: black;
}

.product-card h6, .product-card input[type="hidden"], .product-card a {
   margin-top: 25px;

}

.product-card a i {
   font-size: 20px;
   margin-right: 5px;

}

   .card-img-top {
  max-width: 65%;
  height: auto;
}
.product-card a.disabled {
   cursor: not-allowed;
   opacity: 0.5;
}
.product-card a {
    padding: 0 45px;
}

</style>


<main class="container my-4">
<!-- Filters -->
			{% include 'filters.html' %}
	<div class="container px-4 px-lg-5 mt-5 text-center">
        <div >
            <h2 class="mx-auto my-0 section-heading text-uppercase"></h2>
        </div>
        <div class="row mx-auto mt-5 ">
			<div class="row" id="filteredProducts">
				<p class="ajaxLoader">Loading...</p>
				{% for product in data %}
				<div class="col-lg-3 col-md-6 mb-4 product-box">
						<div class="product-card">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top mx-auto" alt="{{product.title}}"></a>
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
					    <h6>$ <span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span></h6>
				          <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
				          <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
				          <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
				          <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
							  {% if user.is_authenticated %}
<a class="add-to-cart mr-2" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></a>
<a class="add-wishlist ml-2" data-product="{{product.id}}"><i class="fa fa-heart"></i></a>
{% else %}
<a class="disabled"><i class="fa fa-heart"></i></a>
{% endif %}
					  	</div>
				</div>
				{% endfor %}
			</div>
			<p class="my-4 text-center"><a id="loadMore" data-total="{{total_data}}" data-limit="6" class="btn-sm"><i class="fa fa-sync load-more-icon"></i></a></p>
		</div>
	</div>
</main>
{% endblock %}

main/templates/payment-fail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4" id="cartList">
    <p>Payment Failed</p>
</main>
{% endblock %}

main/templates/payment-success.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4" id="cartList">
    <p>Payment Success</p>
</main>
{% endblock %}

main/templates/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
	a.btn-sm {
  text-decoration: none; /* видаляє підкреслення */
  color: #000; /* змінює колір на чорний */
}
.add-to-cart {
  border-top-right-radius: 50px; /* заокруглює верхній правий кут */
  border-bottom-right-radius: 50px; /* заокруглює нижній правий кут */
  border-top-left-radius: 0; /* встановлює нульове заокруглення для верхнього лівого кута */
  border-bottom-left-radius: 0; /* встановлює нульове заокруглення для нижнього лівого кута */
}

.product-card {
   margin-bottom: 20px;

}

.product-card h5 {
   margin-bottom: 0;
}

.product-card h5 a {
   text-decoration: none;
   color: black;
}

.product-card h6, .product-card input[type="hidden"], .product-card a {
   margin-top: 30px;

}

.product-card a i {
   font-size: 20px;
   margin-right: 5px;

}

   .card-img-top {
  max-width: 70%;
  height: auto;
}
.product-card a.disabled {
   cursor: not-allowed;
   opacity: 0.5;
</style>

<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 ">{{data.title}}</h3>

	<div class="row">
		<!-- Images -->
		<div class="col-md-4">
			<img id="zoom_01" data-zoom-image="/media/{{data.productattribute_set.first.image}}" src="/media/{{data.productattribute_set.first.image}}" class="card-img-top" alt="{{data.title}}">
		</div>
		<div class="col-md-8">
			<p>{{data.detail}}</p>

			<table class="table table-bordered">
				<tr>
					<th>Sizes</th>
					<td>
						{% for size in sizes %}
						<a data-price="{{size.price}}" class="btn-sm ">{{size.size__title}}</a>
						{% endfor %}
					</td>
				</tr>
				<tr>
					<th>Price</th>
					<th>$ <span class="product-price-{{data.id}}">{{data.productattribute_set.first.price}}</span></th>
				</tr>
			</table>
			<hr/>
			<div class="input-group my-3" style="width:30%;">
			  <input type="number" value="1" class="form-control product-qty-{{data.id}}" id="productQty" />
			  <div class="input-group-append">
			  	<input type="hidden" class="product-image-{{data.id}}" value="{{data.productattribute_set.first.image}}" />
		          <input type="hidden" class="product-id-{{data.id}}" value="{{data.id}}" />
		          <input type="hidden" class="product-title-{{data.id}}" value="{{data.title}}" />
			    <button class="btn btn-primary btn-sm add-to-cart rounded-right" data-index="{{data.id}}" type="button" id="addToCartBtn"><i class="fa fa-shopping-cart"></i> Add to Cart</button>
</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-6">
			<h3 class="my-3">Detail</h3>
			<!-- Detail -->
			<table class="table table-bordered">
				<tr>
					<th>Brand</th>
					<td><a href="/brand-product-list/{{data.brand.id}}">{{data.brand.title}}</a></td>
				</tr>
				<tr>
					<th>Category</th>
					<td><a href="/category-product-list/{{data.category.id}}">{{data.category.title}}</a></td>
				</tr>
				<tr>
					<th>The composition</th>
					<td>{{data.specs}}</td>
				</tr>
			</table>
		</div>


		<!-- Reviews -->
		<div class="col-md-6">

			{% if user.is_authenticated %}
				{% if canAdd %}
				<h3 class="my-3" data-toggle="modal" data-target="#productReview" type="button" class="reviewBtn">Add Review <i class="fa fa-star text-warning"></i></h3>
				{% endif %}
				{% endif %}
			</h3>
	{% if user.is_authenticated %}
	<!-- Product Review -->
	<div class="modal fade" id="productReview" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="exampleModalLabel">Add Product Review</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
	      	<form method="post" id="addForm" action="{% url 'save-review' data.id %}">
	      		{% csrf_token %}
		      	<table class="table table-bordered">
		      		{{reviewForm.as_table}}
		      		<tr>
		      			<td colspan="2">
		      				<button type="submit" class="btn btn-primary">Submit</button>
		      				<input type="reset" class="btn btn-dark" value="Reset" id="reset" />
		      			</td>
		      		</tr>
		      	</table>
		      	<p class="ajaxRes"></p>
	      </form>
	      </div>
	    </div>
	  </div>
	</div>
	<!-- Product Review End -->
	{% endif %}
			</h3>
			<div class="card">
				<div class="card-body review-list" style="max-height: 400px; overflow: auto;">
					<!-- Detail -->
					{% if reviews %}
						{% for review in reviews %}
						<blockquote class="blockquote text-right">
						  <small>{{review.review_text}}</small>
						  <footer class="blockquote-footer">{{review.user}}
						  	<cite title="Source Title">
						  		{% for star in review.review_rating|ljust:review.review_rating %}
						  		<i class="fa fa-star text-warning"></i>
								{% endfor %}
						  	</cite>
						  </footer>
						</blockquote>
						<hr />
						{% endfor %}
					{% else %}
						<p class="no-data">Add First Review</p>
					{% endif %}
				</div>
			</div>
		</div>
	</div>

	<!-- Related Products -->
	<h3 class="mt-4 mb-3 border-bottom pb-1 text-center">Related Products</h3>
	<div class="row">
		 {% for product in related %}
				<div class="col-lg-4 col-md-6 mb-4 product-box">

						<div class="product-card">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top mx-auto" alt="{{product.title}}"></a>

					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
					    <h6>$ <span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span></h6>


				          <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
				          <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
				          <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
				          <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
							  	{% if user.is_authenticated %}
<a class="add-wishlist" data-product="{{product.id}}"><i class="fa fa-heart"></i></a>
{% else %}
<a class="disabled"><i class="fa fa-heart"></i></a>
{% endif %}
							  	<span class="float-right">
							  		4.5/5
							  		<i class="fa fa-star text-warning"></i>
							  	</span>

					  	</div>

				</div>
				{% endfor %}
	</div>
</main>
<!-- Image Zoom -->
<script src="{% static 'jquery.ez-plus.js' %}"></script>
<script type="text/javascript">
    $('#zoom_01').ezPlus();
</script>

<!-- Add To Cart -->
<script src="{% static 'custom.js' %}"></script>

{% endblock %}